apiVersion: v1
kind: Service
metadata:
  name: friendevent-frontend-service
spec:
  selector:
    app: friendevent-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: friendevent-frontend-deployment
  labels:
    app: friendevent-frontend
spec:
  selector:
    matchLabels:
      app: friendevent-frontend
  template:
    metadata:
      labels:
        app: friendevent-frontend
    spec:
      containers:
      - name: friendevent-frontend
        image: fredericbui/friendevent_frontend:latest
        ports:
        - containerPort: 80